### ISSUE TITLE
App replaces @ characters while key press

### ISSUE THREAD

**Issue by ilyasozkurt** [oxcafedead/barcode-reader-emulator#13]
Hello here!

App is successfully reads the QR codes. In some cases we have @ characters in the value. While passing them app is not successfully sends them. Instead replaces them with \"

![image](https://github.com/user-attachments/assets/3ecff115-450e-4ea2-ab28-3cf6cbaef72a)

Do you have any idea?

Thanks!

**Comment by Kami-prog** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)

**Comment by oxcafedead** [comment]
Can you check that you are actually using "English (US)" keyboard layout?

**Comment by ilyasozkurt** [comment]
@oxcafedead thanks for your help! It works like you mention. But I want to learn that is there a way to make this work for other languages?

**Comment by oxcafedead** [comment]
@ilyasozkurt no, for now this is the defined limitation of the app:
https://github.com/oxcafedead/barcode-reader-emulator?tab=readme-ov-file#known-issueslimitations

Contributions are welcome, but overall, it's not clear how to improve the supported characters set, as there are lots of different keyboard layouts with incompatible signals.

**Comment by ilyasozkurt** [comment]
No worries, thanks for the help and explanation. I'm closing the case.
